### ISSUE TITLE
Final Code Unit Testing In Class Exercise

### ISSUE THREAD

**Issue by rhogewood** [rhogewood/Classwork_Spring2023#16]
Code: https://github.com/rhogewood/Classwork_Spring2023/blob/3844f2f168929602bea70e91a69c670f4727c765/line_coord.py

Unit Test: https://github.com/rhogewood/Classwork_Spring2023/blob/3844f2f168929602bea70e91a69c670f4727c765/test_line_coord.py

**Comment by dward2** [comment]
Looks good.  Thanks.
